name: flashlight_flutter
description: flashlight plugin for Flutter
version: 1.0.3
homepage: https://github.com/vitalii-vov/flashlight_flutter
repository: https://github.com/vitalii-vov/flashlight_flutter
issue_tracker: https://github.com/vitalii-vov/flashlight_flutter/issues

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flashlight_flutter
        pluginClass: FlashlightFlutterPlugin
      ios:
        pluginClass: FlashlightFlutterPlugin

